export * from "./types";
export { toBase64url, fromBase64url } from "./encoding";
export { encryptBytes, decryptBytes } from "./encryption/aesGcm";
export type { EncryptedBlob } from "./encryption/aesGcm";
export { generateVaultKey, generateVaultKeyMaterial, vaultKeyFromBytes, deriveKeyFromPassword } from "./encryption/keyDerivation";
export { encryptVaultBlob, decryptVaultBlob, encryptAsset, decryptAsset } from "./encryption/vaultCipher";
export { splitKey, combineKey, splitVaultKey, combineVaultShares, toKeyShare } from "./sharding/shamir";
export type { RawShare, KeySharingEnvelope } from "./sharding/shamir";
export { serializeShare, parseShare } from "./sharding/shareFormat";
export { refreshShares } from "./sharding/shareRefresh";
export { generateHeirKeyPair, encryptForHeir, decryptForHeir, serializePublicKey, createHeirKeyPair, heirEncrypt, heirDecrypt } from "./encryption/heirKeys";
export { generateOwnerSigningKeyPair, serializePolicyForSigning, canonicalPolicyBytes, canonicalPolicyBytesForSigning, signReleasePolicy, verifyReleasePolicy, signPolicy, verifyPolicy, policySignFields } from "./encryption/policySigning";
export { packageCryptoVault, openCryptoVault } from "./payloads/cryptoVault";
export type { CryptoVaultPayload } from "./payloads/cryptoVault";
export { packageAccessKit, openAccessKit } from "./payloads/accessKit";
export type { AccessKitPayload } from "./payloads/accessKit";
export { packageLegalPacket, openLegalPacket } from "./payloads/legalPacket";
export type { LegalPacketPayload } from "./payloads/legalPacket";
export { rotateVaultKey } from "./lifecycle/rotateKeys";
export { revokeShares } from "./lifecycle/revokeShares";
