#!/usr/bin/env bash
# Regenerates packages/shared/src/contracts/abi.ts from the compiled contracts.
# Run after changing any contract: ./contracts/script/export-abi.sh
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$PATH:$HOME/.foundry/bin"
forge build >/dev/null
forge inspect HeirloomVault abi --json > abi/HeirloomVault.json
forge inspect HeirloomVaultFactory abi --json > abi/HeirloomVaultFactory.json
forge inspect HeirloomAuditAnchor abi --json > abi/HeirloomAuditAnchor.json
out=../packages/shared/src/contracts/abi.ts
{
  echo "// Generated by contracts/script/export-abi.sh. Do not edit by hand."
  echo "export const heirloomVaultAbi = $(cat abi/HeirloomVault.json) as const;"
  echo
  echo "export const heirloomVaultFactoryAbi = $(cat abi/HeirloomVaultFactory.json) as const;"
  echo
  echo "export const heirloomAuditAnchorAbi = $(cat abi/HeirloomAuditAnchor.json) as const;"
} > "$out"
echo "wrote $out"
