/**
 * On-chain contract info shared by the frontend (Member 4), backend (Member 3) and Lit conditions (Member 1).
 * Source of truth: contracts/ (Member 2). ABI is generated by contracts/script/export-abi.sh.
 */
export { heirloomVaultAbi, heirloomVaultFactoryAbi, heirloomAuditAnchorAbi } from "./abi.js";
export { escrowMessages, digest, type EscrowRole } from "./escrow.js";

export const SEPOLIA_CHAIN_ID = 11155111;

export const deployments = {
  sepolia: {
    chainId: SEPOLIA_CHAIN_ID,
    entryPoint: "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
    factory: "0xb99c8F7257Cf03ACDd019EFe7C86bbfCb1d513B3",
    demoVault: "0x8085f0EF193B9dD3F7501394bD3d054c045aB575",
    /** Same setup as demoVault; use for rehearsals so the pitch vault stays untouched. */
    rehearsalVault: "0x0B4E0D3a3c756533acbfe1e64196eA7B731D2bB9",
  },
} as const;

/** Numeric state returned by HeirloomVault.currentState(). */
export const OnChainVaultState = {
  Active: 0,
  Watch: 1,
  TriggerPending: 2,
  Executed: 3,
} as const;
export type OnChainVaultState = (typeof OnChainVaultState)[keyof typeof OnChainVaultState];

export const ETH_TOKEN = "0x0000000000000000000000000000000000000000" as const;
