/**
 * On-chain contract info shared by the frontend (Member 4), backend (Member 3) and Lit conditions (Member 1).
 * Source of truth: contracts/ (Member 2). ABI is generated by contracts/script/export-abi.sh.
 */
export { heirloomVaultAbi, heirloomVaultFactoryAbi, heirloomAuditAnchorAbi } from "./abi.js";
export { escrowMessages, digest, type EscrowRole } from "./escrow.js";
export { b2bMessages, attestTypedData } from "./b2b.js";

export const SEPOLIA_CHAIN_ID = 11155111;

export const deployments = {
  sepolia: {
    chainId: SEPOLIA_CHAIN_ID,
    entryPoint: "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
    /** v2 factory (estate plans, gasless guardian votes, clones). Filled in after deployment. */
    factory: "0x2f1E33Fd68E5a22Eb9cea78383356849F6445807",
    vaultImplementation: "0x89415eE4B3bbd76a9e7E88647F709F55404C0b37",
    /** v2 pitch/demo vault. Filled in after creation. */
    demoVault: "0x43CfaE0d89b26A6dBB235Df788F8f030Ea239EA8",
    /** v2 rehearsal vault. Filled in after creation. */
    rehearsalVault: "0x3bBebae98284897529a8C939FdC5D9bb12303714",
    /** Tamper-evidence anchor for the backend audit log. */
    auditAnchor: "0x13842d3635883c55045c8EF37e0DcBdb2485ae36",
    /** Superseded v1 contracts (single default split), kept for the record. */
    v1: {
      factory: "0xb99c8F7257Cf03ACDd019EFe7C86bbfCb1d513B3",
      demoVault: "0x8085f0EF193B9dD3F7501394bD3d054c045aB575",
      rehearsalVault: "0x0B4E0D3a3c756533acbfe1e64196eA7B731D2bB9",
    },
  },
} as const;

/** Numeric state returned by HeirloomVault.currentState(). */
export const OnChainVaultState = {
  Active: 0,
  Watch: 1,
  TriggerPending: 2,
  Executed: 3,
} as const;
export type OnChainVaultState = (typeof OnChainVaultState)[keyof typeof OnChainVaultState];

export const ETH_TOKEN = "0x0000000000000000000000000000000000000000" as const;
