import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
const categories = ["All", "Planning", "Guardians", "Recovery", "Security"];
const features = [
  { icon: "", title: "A vault that waits", category: "Planning", target: "/setup", text: "Set a check-in rhythm and clear intervention window. Your plan stays dormant while you’re here." },
  { icon: "", title: "People, with boundaries", category: "Guardians", target: "/people", text: "Give guardians, executors, and beneficiaries distinct roles and appropriate access." },
  { icon: "", title: "Release in careful stages", category: "Recovery", target: "/setup", text: "Separate legal instructions, access materials, and crypto recovery into distinct stages." },
  { icon: "⟡", title: "Know what needs attention", category: "Security", target: "/readiness", text: "See setup gaps, current vault state, and the next step in one clear place." },
];
const slides = [
  { eyebrow: "01 / CONTINUITY", title: "A simple check-in keeps your plan in its place.", detail: "Choose a rhythm that works for you. Your vault state stays visible, and your intervention window is clear.", tag: "OWNER CONTROL", link: "/app", icon: "" },
  { eyebrow: "02 / TRUSTED PEOPLE", title: "No one person holds the whole key.", detail: "Set an approval threshold and give each guardian a defined role in the recovery process.", tag: "SHARED OVERSIGHT", link: "/people", icon: "" },
  { eyebrow: "03 / CONTROLLED RELEASE", title: "The right information reaches the right person.", detail: "Keep legal claim guidance, account access, and crypto recovery materials separate.", tag: "SCOPED ACCESS", link: "/setup", icon: "" },
];

function Header() {
  return <header className="landing-nav"><Link to="/" className="landing-brand"><span className="landing-mark">H</span><span>HEIRLOOM<small>DIGITAL LEGACY PROTOCOL</small></span></Link><nav aria-label="Landing page"><a href="#approach">Home</a><a href="#principles">Features</a><a href="#how-it-works">How it works</a><a href="#about">About</a></nav><div className="nav-actions"><Link className="nav-signin" to="/app">Sign in</Link><Link className="nav-cta" to="/setup">Start planning <span>↗</span></Link></div></header>;
}

export default function LandingPage() {
  const reduce = useReducedMotion();
  const [slide, setSlide] = useState(0);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const item = slides[slide];
  const filtered = useMemo(() => features.filter(feature => (category === "All" || feature.category === category) && `${feature.title} ${feature.text} ${feature.category}`.toLowerCase().includes(query.trim().toLowerCase())), [category, query]);

  return <div className="landing-page"><Header/><main>
    <section className="landing-hero" id="approach"><div className="hero-grid" aria-hidden="true"/><motion.div className="hero-copy" initial={reduce ? false : { opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}><div className="hero-overline"><span/> YOUR LEGACY, BY YOUR DESIGN</div><h1>Make space for<br/><em>what matters.</em></h1><p>Put thoughtful instructions around your digital life. Choose who you trust, what they can access, and when.</p><form className="hero-search" onSubmit={event => { event.preventDefault(); document.querySelector("#principles")?.scrollIntoView({ behavior: reduce ? "instant" : "smooth" }); }}><input value={query} onChange={event => setQuery(event.target.value)} aria-label="Search Heirloom features" placeholder="Search guardians, recovery, check-ins…"/><button type="submit">Explore <span>↗</span></button></form><div className="hero-chips" aria-label="Filter features by topic">{categories.slice(1).map(name => <button type="button" key={name} className={category === name ? "chosen" : ""} aria-pressed={category === name} onClick={() => { setCategory(category === name ? "All" : name); document.querySelector("#principles")?.scrollIntoView({ behavior: reduce ? "instant" : "smooth" }); }}>{name}</button>)}</div><div className="hero-microcopy">Privacy-minded planning <i/> No single person can trigger a release</div></motion.div><div className="hero-bottom-label"><span>01 — A PLAN THAT FOLLOWS YOUR INTENT</span><a href="#principles">SCROLL TO EXPLORE ↓</a></div></section>

    <section className="trust-strip" aria-label="Heirloom principles"><div><span>YOUR PLAN</span><b>Personal <i>·</i> Clear <i>·</i> Considered</b></div><div><span>YOUR PEOPLE</span><b>Guardians <i>·</i> Executors <i>·</i> Beneficiaries</b></div><div className="trust-badge"><b>Security-aware<br/>by design</b></div></section>

    <section className="intro-section" id="principles"><div className="section-heading-center"><span className="light-kicker">A PLAN THAT RESPECTS YOUR INTENT</span><h2>Give the important things<br/><em>a thoughtful way forward.</em></h2><p>Start with the parts of digital life that matter to you, then make each next step clear.</p></div><div className="feature-toolbar"><span>{query || category !== "All" ? `${filtered.length} matching ${filtered.length === 1 ? "feature" : "features"}` : "A few ways to get started"}</span><button type="button" onClick={() => { setQuery(""); setCategory("All"); }} disabled={!query && category === "All"}>Clear filters <span>×</span></button></div>{filtered.length ? <div className="feature-grid">{filtered.map((feature, i) => <motion.article className="feature-card" key={feature.title} initial={reduce ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ delay: i * .06 }}><Link to={feature.target} className="feature-link"><div className={`feature-art art-${i % 4}`} aria-hidden="true"><span>{feature.icon}</span><i/><b/></div><div className="feature-card-bottom"><div><span className="feature-category">{feature.category}</span><h3>{feature.title}</h3></div><span className="feature-arrow" aria-hidden="true">→</span></div><p>{feature.text}</p></Link></motion.article>)}</div> : <div className="feature-empty"><b>No matching topics yet</b><p>Try “guardians”, “recovery”, or clear the filters to see every feature.</p><button onClick={() => { setQuery(""); setCategory("All"); }}>Show all features</button></div>}</section>

    <section className="story-section" id="how-it-works"><div className="story-heading"><span className="light-kicker">HOW HEIRLOOM WORKS</span><h2>Explore the steps<br/><em>that keep intent clear.</em></h2><p>From your first check-in to carefully scoped recovery, each part has a purpose.</p><div className="carousel-controls"><button aria-label="Previous feature" onClick={() => setSlide((slide + slides.length - 1) % slides.length)}>←</button><span>0{slide + 1} <i>/</i> 0{slides.length}</span><button aria-label="Next feature" onClick={() => setSlide((slide + 1) % slides.length)}>→</button></div></div><div className="story-showcase"><div className="carousel-track" aria-label="Heirloom planning steps"><div className="carousel-loop">{[...slides, ...slides].map((s, i) => <article className={`carousel-card ${i % slides.length === slide ? "selected" : ""}`} key={`${s.eyebrow}-${i}`} aria-hidden={i >= slides.length}><span className="carousel-eyebrow">{s.eyebrow}</span><Link to={s.link} className="carousel-card-link" tabIndex={i >= slides.length ? -1 : 0} onClick={() => setSlide(i % slides.length)}><div className={`card-visual visual-${i % slides.length}`} aria-hidden="true"><div className="visual-glow"/><div className="visual-object">{s.icon}</div><div className="visual-dash dash-a"/><div className="visual-dash dash-b"/><div className="visual-orbit"/></div><span className="carousel-tag">{s.tag}</span><h3>{s.title}<span> ↗</span></h3><p>{s.detail}</p></Link><span className="carousel-card-num">0{i % slides.length + 1}</span></article>)}</div></div><AnimatePresence mode="wait"><motion.div key={slide} className="carousel-caption" initial={reduce ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }}><span>{item.eyebrow}</span><b>{item.title}</b></motion.div></AnimatePresence></div></section>

    <section className="closing-cta" id="about"><div className="closing-glow"/><span className="light-kicker">START WITH WHAT MATTERS MOST</span><h2>Make your wishes<br/><em>easier to follow.</em></h2><p>Begin with a simple overview. Add your trusted people and build your plan at your own pace.</p><Link to="/setup" className="primary-cta">Start your plan <span>↗</span></Link><div className="closing-meta"><span>PRIVATE BY DESIGN</span><span>BUILT AROUND YOUR CHOICES</span><span>ALWAYS IN YOUR CONTROL</span></div></section>
    <footer className="landing-footer"><Link to="/" className="landing-brand"><span className="landing-mark">H</span><span>HEIRLOOM<small>DIGITAL LEGACY PROTOCOL</small></span></Link><span>Thoughtfully planned. Personally yours.</span><Link to="/app">Sign in ↗</Link></footer>
  </main></div>;
}
